### ISSUE TITLE
Crash bug when using MuLTI_TEM_1D.m

### ISSUE THREAD

**Issue by jchaput82** [eespr/MuLTI-TEM#2]
When setting num_layers = 1 on line 106 (i.e., perform a 1D inversion without layering constraints), the code crashes while attempting to run the LEROY_TEM mex, with an output complaining about the "thickness" variable. Setting num_layers to 2 or 3 appears to work as intended.
Cheers

Julien

**Comment by eespr** [comment]
This has now been fixed and updated.
